server:
  port: 8088
logging:
  level:
    com:
      example:
        demo: debug
spring:
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: 123
management:
  security:
    enabled: false #关掉安全认证
  port: 8088
  endpoints:
    web:
      exposure:
        include: "*"